AWSTemplateFormatVersion: 2010-09-09
Description:  SSH Security Group

Resources:

  Instance:
    # Corregir
    CreationPolicy:
        ResourceSignal:
          Timeout: PT5M

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: ami-005fc0f236362e99f
        InstanceType: t2.micro
        SecurityGroupIds: 
          - !Ref InstanceSecurityGroup
        KeyName: vockey
        Tags:
          - Key: Name
            Value: Tomcat
        UserData:
          Fn::Base64: !Sub |
          # ***** COMPLETAR ***** CFN-INIT, CFN-SIGNAL PARA QUE NO SE PARE CUANDO TARDA MUCHO EN INSTALAR
            #! /bin/bash
            sed -i "s/#\$nrconf{kernelhints} = -1;/\$nrconf{kernelhints} = -1;/g" /etc/needrestart/needrestart.conf
            apt update
            apt ugrade -y
            useradd -m -d /opt/tomcat -U -s /bin/false tomcat
            apt install openjdk-21-jdk -y
            cd /tmp
            wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
            tar xzvf apache-tomcat-11.0.2.tar.gz -C /opt/tomcat --strip-components=1
            chown -R tomcat:tomcat /opt/tomcat/
            chmod -R u+x /opt/tomcat/bin
            sed -i '/<\/tomcat-users>/i \<role rolename="manager-gui" />\n<user username="manager" password="manager_password" roles="manager-gui" />\n\n<role rolename="admin-gui" />\n<user username="admin" password="admin_password" roles="manager-gui,admin-gui" />' /opt/tomcat/conf/tomcat-users.xml
            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/manager/META-INF/context.xml
            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/manager/META-INF/context.xml
            echo '[Unit]
            Description=Tomcat
            After=network.target
            [Service]
            Type=forking
            User=tomcat
            Group=tomcat
            Environment="JAVA_HOME=/usr/lib/jvm/java-1.21.0-openjdk-amd64"
            Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
            Environment="CATALINA_BASE=/opt/tomcat"
            Environment="CATALINA_HOME=/opt/tomcat"
            Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
            Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh
            RestartSec=10
            Restart=always
            [Install]
            WantedBy=multi-user.target' | sudo tee /etc/systemd/system/tomcat.service
            systemctl daemon-reload
            systemctl enable tomcat
            systemctl start tomcat

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSHSecurityGroup
      GroupName: SSHSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
